# .github/workflows/pake-build.yml
name: Build Pake App

on:
  repository_dispatch:
    types: [build-pake-app]

env:
  SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
  SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install Dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libayatana-appindicator3-dev librsvg2-dev

      - name: Install Pake
        run: |
          # Clone repository
          git clone https://github.com/tw93/Pake.git
          cd Pake
          cd src-tauri
          
          # Show current Cargo.toml
          echo "Current Cargo.toml:"
          cat Cargo.toml
          
          # Remove the oauth dependency using perl (more reliable than sed)
          perl -i -ne 'print unless /tauri-plugin-oauth/' Cargo.toml
          
          # Show modified Cargo.toml
          echo "Modified Cargo.toml:"
          cat Cargo.toml
          
          # Clean any previous builds
          cargo clean
          
          # Update dependencies
          cargo update
          
          # Build the project
          cargo build --release --verbose
          
          # Install binary
          sudo cp target/release/pake /usr/local/bin/ || cp target/release/pake ~/.cargo/bin/
        shell: bash

      - name: Build with Pake
        run: |
          pake ${{ github.event.client_payload.url }} \
          --name "${{ github.event.client_payload.name }}" \
          --height 800 \
          --width 1280

      - name: Package Apps
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            Compress-Archive -Path "*.exe" -DestinationPath "${{ github.event.client_payload.name }}-windows.zip"
          elif [ "${{ matrix.os }}" = "macos-latest" ]; then
            zip -r "${{ github.event.client_payload.name }}-macos.zip" *.app
          else
            zip -r "${{ github.event.client_payload.name }}-linux.zip" *.AppImage
          fi
        shell: bash

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.client_payload.name }}-${{ matrix.os }}
          path: ${{ github.event.client_payload.name }}-*.zip

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: success()
        with:
          files: ${{ github.event.client_payload.name }}-*.zip
          name: ${{ github.event.client_payload.name }}
          tag_name: release-${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Supabase Status
        run: |
          curl -X PATCH "${{ env.SUPABASE_URL }}/rest/v1/pake_apps" \
          -H "apikey: ${{ env.SUPABASE_ANON_KEY }}" \
          -H "Content-Type: application/json" \
