# .github/workflows/pake-build.yml
name: Build Pake App

on:
  repository_dispatch:
    types: [build-pake-app]

env:
  SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
  SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install Dependencies (macOS)
        run: |
          brew install node
          brew install rust

      - name: Clone Pake
        run: |
          git clone --depth 1 --branch v2.0.0 https://github.com/tw93/Pake.git
          cd Pake
          npm install

      - name: Modify Cargo.toml
        run: |
          cd Pake/src-tauri
          cat > Cargo.toml << 'EOL'
          [package]
          name = "app"
          version = "0.1.0"
          description = "A Tauri App"
          authors = ["you"]
          license = ""
          repository = ""
          edition = "2021"
          rust-version = "1.57"

          [build-dependencies]
          tauri-build = { version = "1.2" }

          [dependencies]
          serde_json = "1.0"
          serde = { version = "1.0", features = ["derive"] }
          tauri = { version = "1.2", features = ["api-all"] }
          webbrowser = "0.8"
          wry = "0.24"

          [features]
          default = ["custom-protocol"]
          custom-protocol = ["tauri/custom-protocol"]
          EOL

      - name: Create tauri.conf.json
        run: |
          cd Pake/src-tauri
          cat > tauri.conf.json << 'EOL'
          {
            "build": {
              "beforeDevCommand": "",
              "beforeBuildCommand": "",
              "devPath": "../src",
              "distDir": "../src"
            },
            "package": {
              "productName": "${{ github.event.client_payload.name }}",
              "version": "0.1.0"
            },
            "tauri": {
              "allowlist": {
                "all": true
              },
              "bundle": {
                "active": true,
                "category": "DeveloperTool",
                "copyright": "",
                "deb": {
                  "depends": []
                },
                "icon": [
                  "icons/32x32.png",
                  "icons/128x128.png",
                  "icons/128x128@2x.png",
                  "icons/icon.icns",
                  "icons/icon.ico"
                ],
                "identifier": "com.tauri.dev",
                "longDescription": "",
                "macOS": {
                  "entitlements": null,
                  "exceptionDomain": "",
                  "frameworks": [],
                  "providerShortName": null,
                  "signingIdentity": null
                },
                "resources": [],
                "shortDescription": "",
                "targets": "all",
                "windows": {
                  "certificateThumbprint": null,
                  "digestAlgorithm": "sha256",
                  "timestampUrl": ""
                }
              },
              "security": {
                "csp": "default-src 'self' 'unsafe-eval' 'unsafe-inline' data: filesystem: ws: wss: http: https:"
              },
              "windows": [
                {
                  "fullscreen": false,
                  "height": 800,
                  "resizable": true,
                  "title": "${{ github.event.client_payload.name }}",
                  "width": 1280
                }
              ]
            }
          }
          EOL

      - name: Create Source Files
        run: |
          cd Pake/src-tauri/src
          cat > main.rs << 'EOL'
          #![cfg_attr(all(not(debug_assertions), target_os = "windows"), windows_subsystem = "windows")]

          use tauri::{CustomMenuItem, Menu, MenuItem, Submenu};

          fn main() {
            let ctx = tauri::generate_context!();
            tauri::Builder::default()
              .menu(
                Menu::new()
                  .add_submenu(Submenu::new(
                    "File",
                    Menu::new().add_native_item(MenuItem::Quit),
                  ))
              )
              .run(ctx)
              .expect("error while running tauri application");
          }
          EOL

      - name: Build App
        run: |
          cd Pake/src-tauri
          mkdir -p icons
          cargo build --release

      - name: Package App
        run: |
          cd Pake/src-tauri/target/release
          zip -r "../../../${{ github.event.client_payload.name }}-macos.zip" *.app || zip -r "../../../${{ github.event.client_payload.name }}-macos.zip" app

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: success()
        with:
          files: Pake/${{ github.event.client_payload.name }}-macos.zip
          name: ${{ github.event.client_payload.name }}
          tag_name: release-${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Supabase Status
        run: |
          curl -X PATCH "${{ env.SUPABASE_URL }}/rest/v1/pake_apps" \
            -H "apikey: ${{ env.SUPABASE_ANON_KEY }}" \
            -H "Content-Type: application/json" \
